[project]
name = "nightrunner-backend"
version = "0.1.0"
dependencies = [
    "falcon[asgi]",
    "uvicorn",
    "aiosqlite",
    "psycopg[binary]",
    "psycopg-pool",
    "pyjwt[crypto]",
    "pydantic",
    "pydantic-settings",
    "uuid6",
    "python-dotenv",
    "httpx",
]

[project.optional-dependencies]
test = [
    "pytest",
    "pytest-asyncio",
    "schemathesis",
    "cryptography",
]

[tool.setuptools]
packages = ["nightrunner_backend"]

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[tool.pytest.ini_options]
asyncio_mode = "auto"
testpaths = ["tests"]
python_files = "test_*.py"
